In [1]:
import pandas as pd

In [5]:
df = pd.read_csv("C:\\Users\\rohin\\Sucide Project\\Feature Engineering Ready Data\\feature_engineering_ready_data.csv")
df.head()

,Year,AlcoholConsumption,HomicideRate,GDP_per_capita,"Unemployment, total (% of total labor force) (modeled ILO estimate)_x",SuicideRate
0,2000,8.742056,45.012212,3217.846934,22.714,13.132524
1,2001,8.742056,45.090413,2847.151919,22.605,13.245669
2,2002,8.483838,47.472567,2688.236760,22.547,14.598869
3,2003,8.366666,44.799503,4062.217560,22.629,15.759870
4,2004,8.343871,44.530240,5221.463337,22.538,16.074981

In [6]:
predictors = [
    "AlcoholConsumption",
    "HomicideRate",
    "GDP_per_capita",
    "Unemployment, total (% of total labor force) (modeled ILO estimate)_x"
]

target = "SuicideRate"

In [7]:
for col in predictors:
    df[col + "_lag1"] = df[col].shift(1)

In [8]:
for col in predictors:
    df[col + "_lag2"] = df[col].shift(2)

In [9]:
for col in predictors:
    df[col + "_roll3"] = df[col].rolling(window=3).mean()

In [10]:
df["Year_scaled"] = df["Year"] - df["Year"].min()

In [11]:
df = df.sort_values("Year")
df = df.interpolate(method='linear', limit_direction='both')

In [12]:
df.isna().sum()

Year                                                                           0
AlcoholConsumption                                                             0
HomicideRate                                                                   0
GDP_per_capita                                                                 0
Unemployment, total (% of total labor force) (modeled ILO estimate)_x          0
SuicideRate                                                                    0
AlcoholConsumption_lag1                                                        0
HomicideRate_lag1                                                              0
GDP_per_capita_lag1                                                            0
Unemployment, total (% of total labor force) (modeled ILO estimate)_x_lag1     0
AlcoholConsumption_lag2                                                        0
HomicideRate_lag2                                                              0
GDP_per_capita_lag2                                                            0
Unemployment, total (% of total labor force) (modeled ILO estimate)_x_lag2     0
AlcoholConsumption_roll3                                                       0
HomicideRate_roll3                                                             0
GDP_per_capita_roll3                                                           0
Unemployment, total (% of total labor force) (modeled ILO estimate)_x_roll3    0
Year_scaled                                                                    0
dtype: int64

In [13]:
df.head()

,Year,AlcoholConsumption,HomicideRate,GDP_per_capita,"Unemployment, total (% of total labor force) (modeled ILO estimate)_x",SuicideRate,AlcoholConsumption_lag1,HomicideRate_lag1,GDP_per_capita_lag1,"Unemployment, total (% of total labor force) (modeled ILO estimate)_x_lag1",AlcoholConsumption_lag2,HomicideRate_lag2,GDP_per_capita_lag2,"Unemployment, total (% of total labor force) (modeled ILO estimate)_x_lag2",AlcoholConsumption_roll3,HomicideRate_roll3,GDP_per_capita_roll3,"Unemployment, total (% of total labor force) (modeled ILO estimate)_x_roll3",Year_scaled
0,2000,8.742056,45.012212,3217.846934,22.714,13.132524,8.742056,45.012212,3217.846934,22.714,8.742056,45.012212,3217.846934,22.714,8.655983,45.858397,2917.745205,22.622000,0
1,2001,8.742056,45.090413,2847.151919,22.605,13.245669,8.742056,45.012212,3217.846934,22.714,8.742056,45.012212,3217.846934,22.714,8.655983,45.858397,2917.745205,22.622000,1
2,2002,8.483838,47.472567,2688.236760,22.547,14.598869,8.742056,45.090413,2847.151919,22.605,8.742056,45.012212,3217.846934,22.714,8.655983,45.858397,2917.745205,22.622000,2
3,2003,8.366666,44.799503,4062.217560,22.629,15.759870,8.483838,47.472567,2688.236760,22.547,8.742056,45.090413,2847.151919,22.605,8.530853,45.787494,3199.202080,22.593667,3
4,2004,8.343871,44.530240,5221.463337,22.538,16.074981,8.366666,44.799503,4062.217560,22.629,8.483838,47.472567,2688.236760,22.547,8.398125,45.600770,3990.639219,22.571333,4

In [14]:
output_path = "final_model_dataset_FEATURES.csv"
df.to_csv(output_path, index=False)

output_path

'final_model_dataset_FEATURES.csv'