In [1]:
import pandas as pd

In [3]:
suicide = pd.read_csv("C:\\Users\\rohin\\Sucide Project\\Cleaned Data\\cleaned_suicide_rate.csv")
alcohol = pd.read_csv("C:\\Users\\rohin\\Sucide Project\\Cleaned Data\\cleaned_alcohol_consumption.csv")
homicide = pd.read_csv("C:\\Users\\rohin\\Sucide Project\\Cleaned Data\\cleaned_homicide_rate.csv")
gdp = pd.read_csv("C:\\Users\\rohin\\Sucide Project\\Cleaned Data\\cleaned_gdp_per_capita.csv")

# Optional predictors
unemployment_health = pd.read_csv("C:\\Users\\rohin\\Sucide Project\\Cleaned Data\\cleaned_unemployment_health.csv")
unemployment_meta = pd.read_csv("C:\\Users\\rohin\\Sucide Project\\Cleaned Data\\unemploymentvshealthmetadatacleaned.csv")

In [4]:
suicide.head()
alcohol.head()
homicide.head()
gdp.head()

   Year  GDP_per_capita
0  2000     3217.846934
1  2001     2847.151919
2  2002     2688.236760
3  2003     4062.217560
4  2004     5221.463337

In [5]:
suicide = suicide.rename(columns={"Time": "Year"})

In [6]:
suicide["Year"] = suicide["Year"].astype(int)
alcohol["Year"] = alcohol["Year"].astype(int)
homicide["Year"] = homicide["Year"].astype(int)
gdp["Year"] = gdp["Year"].astype(int)

# Optional ones
unemployment_health["Year"] = unemployment_health["Year"].astype(int)
unemployment_meta["Year"] = unemployment_meta["Year"].astype(int)

In [7]:
merged = suicide.copy()

In [8]:
merged = merged.merge(alcohol, on="Year", how="outer")

In [9]:
merged = merged.merge(homicide, on="Year", how="outer")

In [10]:
merged = merged.merge(gdp, on="Year", how="outer")

In [11]:
merged = merged.merge(unemployment_health, on="Year", how="outer")
merged = merged.merge(unemployment_meta, on="Year", how="outer")

In [12]:
merged = merged.sort_values("Year").reset_index(drop=True)
merged.head(15)

,Year,SuicideRate,AlcoholConsumption,HomicideRate,GDP_per_capita,Current health expenditure (% of GDP)_x,Current health expenditure per capita (current US$)_x,"Unemployment, total (% of total labor force) (modeled ILO estimate)_x",Current health expenditure (% of GDP)_y,Current health expenditure per capita (current US$)_y,"Unemployment, total (% of total labor force) (modeled ILO estimate)_y"
0,1975,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1976,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1977,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1978,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1979,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1981,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1984,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1985,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1986,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1988,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1989,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
merged.tail(15)

,Year,SuicideRate,AlcoholConsumption,HomicideRate,GDP_per_capita,Current health expenditure (% of GDP)_x,Current health expenditure per capita (current US$)_x,"Unemployment, total (% of total labor force) (modeled ILO estimate)_x",Current health expenditure (% of GDP)_y,Current health expenditure per capita (current US$)_y,"Unemployment, total (% of total labor force) (modeled ILO estimate)_y"
35,2010,NaN,8.239292,14.266698,7973.471958,7.793582,621.419067,24.683,7.793582,621.419067,24.683
36,2011,NaN,8.336959,13.718138,8646.055711,7.944344,686.872437,24.639,7.944344,686.872437,24.639
37,2012,NaN,8.421343,13.446773,8076.976785,8.004289,646.499207,24.727,8.004289,646.499207,24.727
38,2013,NaN,8.441097,13.408549,7331.654674,8.103223,593.801575,24.561,8.103223,593.801575,24.561
39,2014,NaN,8.451979,13.510317,6856.731371,7.871366,539.307800,24.890,7.871366,539.307800,24.890
40,2015,NaN,8.443988,13.704022,6112.273825,8.053042,491.906525,25.149,8.053042,491.906525,25.149
41,2016,NaN,8.397732,13.955669,5651.205852,8.079594,456.569366,26.536,8.079594,456.569366,26.536
42,2017,NaN,NaN,14.477758,6618.335083,7.977112,527.520203,27.035,7.977112,527.520203,27.035
43,2018,NaN,8.451479,13.546167,6914.178032,8.081965,558.801392,26.906,8.081965,558.801392,26.906
44,2019,NaN,7.939926,13.508287,6533.711210,8.246526,538.804260,28.468,8.246526,538.804260,28.468
45,2020,NaN,NaN,12.961973,5580.603831,9.013292,503.467590,29.217,9.013292,503.467590,29.217
46,2021,NaN,7.791870,12.533244,6843.399419,8.674328,592.534180,34.007,8.674328,592.534180,34.007
47,2022,NaN,7.791870,NaN,6523.410978,8.770866,569.840759,33.268,8.770866,569.840759,33.268
48,2023,NaN,NaN,NaN,NaN,NaN,NaN,32.098,NaN,NaN,32.098
49,2024,NaN,NaN,NaN,NaN,NaN,NaN,33.168,NaN,NaN,33.168

In [14]:
merged.isnull().sum()

Year                                                                      0
SuicideRate                                                              42
AlcoholConsumption                                                       29
HomicideRate                                                             28
GDP_per_capita                                                           27
Current health expenditure (% of GDP)_x                                  27
Current health expenditure per capita (current US$)_x                    27
Unemployment, total (% of total labor force) (modeled ILO estimate)_x    16
Current health expenditure (% of GDP)_y                                  27
Current health expenditure per capita (current US$)_y                    27
Unemployment, total (% of total labor force) (modeled ILO estimate)_y    16
dtype: int64

In [15]:
merged.to_csv("final_model_dataset.csv", index=False)