In [80]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

In [81]:
df_sa = pd.read_csv("C:\\Users\\rohin\\Sucide Project\\Feature Engineering\\final_model_dataset_FEATURES.csv")

df_sa.head()

,Year,AlcoholConsumption,HomicideRate,GDP_per_capita,"Unemployment, total (% of total labor force) (modeled ILO estimate)_x",SuicideRate,AlcoholConsumption_lag1,HomicideRate_lag1,GDP_per_capita_lag1,"Unemployment, total (% of total labor force) (modeled ILO estimate)_x_lag1",AlcoholConsumption_lag2,HomicideRate_lag2,GDP_per_capita_lag2,"Unemployment, total (% of total labor force) (modeled ILO estimate)_x_lag2",AlcoholConsumption_roll3,HomicideRate_roll3,GDP_per_capita_roll3,"Unemployment, total (% of total labor force) (modeled ILO estimate)_x_roll3",Year_scaled
0,2000,8.742056,45.012212,3217.846934,22.714,13.132524,8.742056,45.012212,3217.846934,22.714,8.742056,45.012212,3217.846934,22.714,8.655983,45.858397,2917.745205,22.622000,0
1,2001,8.742056,45.090413,2847.151919,22.605,13.245669,8.742056,45.012212,3217.846934,22.714,8.742056,45.012212,3217.846934,22.714,8.655983,45.858397,2917.745205,22.622000,1
2,2002,8.483838,47.472567,2688.236760,22.547,14.598869,8.742056,45.090413,2847.151919,22.605,8.742056,45.012212,3217.846934,22.714,8.655983,45.858397,2917.745205,22.622000,2
3,2003,8.366666,44.799503,4062.217560,22.629,15.759870,8.483838,47.472567,2688.236760,22.547,8.742056,45.090413,2847.151919,22.605,8.530853,45.787494,3199.202080,22.593667,3
4,2004,8.343871,44.530240,5221.463337,22.538,16.074981,8.366666,44.799503,4062.217560,22.629,8.483838,47.472567,2688.236760,22.547,8.398125,45.600770,3990.639219,22.571333,4

In [82]:
df_sa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 19 columns):
 #   Column                                                                       Non-Null Count  Dtype
---  ------                                                                       --------------  -----
 0   Year                                                                         25 non-null     int64
 1   AlcoholConsumption                                                           25 non-null     float64
 2   HomicideRate                                                                 25 non-null     float64
 3   GDP_per_capita                                                               25 non-null     float64
 4   Unemployment, total (% of total labor force) (modeled ILO estimate)_x        25 non-null     float64
 5   SuicideRate                                                                  25 non-null     float64
 6   AlcoholConsumption_lag1                                                      25 non-null     float64
 7   HomicideRate_lag1                                                            25 non-null     float64
 8   GDP_per_capita_lag1                                                          25 non-null     float64
 9   Unemployment, total (% of total labor force) (modeled ILO estimate)_x_lag1   25 non-null     float64
 10  AlcoholConsumption_lag2                                                      25 non-null     float64
 11  HomicideRate_lag2                                                            25 non-null     float64
 12  GDP_per_capita_lag2                                                          25 non-null     float64
 13  Unemployment, total (% of total labor force) (modeled ILO estimate)_x_lag2   25 non-null     float64
 14  AlcoholConsumption_roll3                                                     25 non-null     float64
 15  HomicideRate_roll3                                                           25 non-null     float64
 16  GDP_per_capita_roll3                                                         25 non-null     float64
 17  Unemployment, total (% of total labor force) (modeled ILO estimate)_x_roll3  25 non-null     float64
 18  Year_scaled                                                                  25 non-null     int64
dtypes: float64(17), int64(2)
memory usage: 3.8 KB

In [83]:
df_suicide = pd.read_csv("C:\\Users\\rohin\\Sucide Project\\Raw Datasets\\16BBF41_ALL_LATEST.csv")

df_suicide.head()

,IND_ID,IND_CODE,IND_UUID,IND_PER_CODE,DIM_TIME,DIM_TIME_TYPE,DIM_GEO_CODE_M49,DIM_GEO_CODE_TYPE,DIM_PUBLISH_STATE_CODE,IND_NAME,GEO_NAME_SHORT,DIM_SEX,DIM_AGE,RATE_PER_100000_N,RATE_PER_100000_NL,RATE_PER_100000_NU
0,16BBF41SDGSUICIDE,SDGSUICIDE,16BBF41,SDGSUICIDE,2000,YEAR,1,GLOBAL,PUBLISHED,Suicide deaths,World,FEMALE,TOTAL,8.800814,6.116331,10.530853
1,16BBF41SDGSUICIDE,SDGSUICIDE,16BBF41,SDGSUICIDE,2000,YEAR,1,GLOBAL,PUBLISHED,Suicide deaths,World,MALE,TOTAL,16.199777,13.242620,18.696946
2,16BBF41SDGSUICIDE,SDGSUICIDE,16BBF41,SDGSUICIDE,2000,YEAR,1,GLOBAL,PUBLISHED,Suicide deaths,World,TOTAL,TOTAL,12.520139,9.695973,14.631939
3,16BBF41SDGSUICIDE,SDGSUICIDE,16BBF41,SDGSUICIDE,2000,YEAR,4,COUNTRY,PUBLISHED,Suicide deaths,Afghanistan,FEMALE,TOTAL,2.910393,1.485886,5.835807
4,16BBF41SDGSUICIDE,SDGSUICIDE,16BBF41,SDGSUICIDE,2000,YEAR,4,COUNTRY,PUBLISHED,Suicide deaths,Afghanistan,MALE,TOTAL,5.793457,3.109532,9.464380

In [84]:
df_suicide.columns

Index(['IND_ID', 'IND_CODE', 'IND_UUID', 'IND_PER_CODE', 'DIM_TIME',
       'DIM_TIME_TYPE', 'DIM_GEO_CODE_M49', 'DIM_GEO_CODE_TYPE',
       'DIM_PUBLISH_STATE_CODE', 'IND_NAME', 'GEO_NAME_SHORT', 'DIM_SEX',
       'DIM_AGE', 'RATE_PER_100000_N', 'RATE_PER_100000_NL',
       'RATE_PER_100000_NU'],
      dtype='object')

In [85]:
df_suicide['DIM_SEX'].unique()

array(['FEMALE', 'MALE', 'TOTAL'], dtype=object)

In [86]:
df_suicide = df_suicide[
    (df_suicide['DIM_SEX'] == 'TOTAL') &
    (df_suicide['DIM_AGE'] == 'TOTAL')
]

In [87]:
len(df_suicide)
df_suicide.head()

,IND_ID,IND_CODE,IND_UUID,IND_PER_CODE,DIM_TIME,DIM_TIME_TYPE,DIM_GEO_CODE_M49,DIM_GEO_CODE_TYPE,DIM_PUBLISH_STATE_CODE,IND_NAME,GEO_NAME_SHORT,DIM_SEX,DIM_AGE,RATE_PER_100000_N,RATE_PER_100000_NL,RATE_PER_100000_NU
2,16BBF41SDGSUICIDE,SDGSUICIDE,16BBF41,SDGSUICIDE,2000,YEAR,1,GLOBAL,PUBLISHED,Suicide deaths,World,TOTAL,TOTAL,12.520139,9.695973,14.631939
5,16BBF41SDGSUICIDE,SDGSUICIDE,16BBF41,SDGSUICIDE,2000,YEAR,4,COUNTRY,PUBLISHED,Suicide deaths,Afghanistan,TOTAL,TOTAL,4.356148,2.296752,7.646272
8,16BBF41SDGSUICIDE,SDGSUICIDE,16BBF41,SDGSUICIDE,2000,YEAR,8,COUNTRY,PUBLISHED,Suicide deaths,Albania,TOTAL,TOTAL,4.780500,3.528174,6.517821
11,16BBF41SDGSUICIDE,SDGSUICIDE,16BBF41,SDGSUICIDE,2000,YEAR,12,COUNTRY,PUBLISHED,Suicide deaths,Algeria,TOTAL,TOTAL,4.183849,2.304831,6.312259
14,16BBF41SDGSUICIDE,SDGSUICIDE,16BBF41,SDGSUICIDE,2000,YEAR,24,COUNTRY,PUBLISHED,Suicide deaths,Angola,TOTAL,TOTAL,9.115151,5.533850,13.312611

In [88]:
df_suicide = df_suicide[['GEO_NAME_SHORT', 'DIM_TIME', 'RATE_PER_100000_N']]
df_suicide = df_suicide.rename(columns={'Value': 'SuicideRate'})

In [89]:
df_alcohol = pd.read_csv("C:\\Users\\rohin\\Sucide Project\\Raw Datasets\\EE6F72A_ALL_LATEST.csv")

df_alcohol.head()

,IND_ID,IND_CODE,IND_UUID,IND_PER_CODE,DIM_TIME,DIM_TIME_TYPE,DIM_GEO_CODE_M49,DIM_GEO_CODE_TYPE,DIM_PUBLISH_STATE_CODE,IND_NAME,GEO_NAME_SHORT,DIM_SEX,RATE_PER_CAPITA_N,RATE_PER_CAPITA_NL,RATE_PER_CAPITA_NU
0,EE6F72ASA_0000001688,SA_0000001688,EE6F72A,SA_0000001688,2003,YEAR,192,COUNTRY,PUBLISHED,Alcohol consumption (age 15+),Cuba,TOTAL,5.885221,4.503071,7.410578
1,EE6F72ASA_0000001688,SA_0000001688,EE6F72A,SA_0000001688,2003,YEAR,196,COUNTRY,PUBLISHED,Alcohol consumption (age 15+),Cyprus,TOTAL,7.142592,5.563809,8.754144
2,EE6F72ASA_0000001688,SA_0000001688,EE6F72A,SA_0000001688,2003,YEAR,199,CLASSIFICATION,PUBLISHED,Alcohol consumption (age 15+),Least developed countries,TOTAL,2.029877,1.895321,2.216005
3,EE6F72ASA_0000001688,SA_0000001688,EE6F72A,SA_0000001688,2003,YEAR,202,REGION,PUBLISHED,Alcohol consumption (age 15+),Sub-Saharan Africa,TOTAL,3.860405,3.588745,4.177033
4,EE6F72ASA_0000001688,SA_0000001688,EE6F72A,SA_0000001688,2003,YEAR,203,COUNTRY,PUBLISHED,Alcohol consumption (age 15+),Czechia,TOTAL,14.557763,12.680295,16.571871

In [90]:
df_alcohol = df_alcohol[['GEO_NAME_SHORT', 'DIM_TIME', 'RATE_PER_CAPITA_N']]
df_alcohol = df_alcohol.rename(columns={'Value': 'AlcoholConsumption'})

In [91]:
df_homicide = pd.read_csv("C:\\Users\\rohin\\Sucide Project\\Raw Datasets\\361734E_ALL_LATEST.csv")
df_homicide.head()

,IND_ID,IND_CODE,IND_UUID,IND_PER_CODE,DIM_TIME,DIM_TIME_TYPE,DIM_GEO_CODE_M49,DIM_GEO_CODE_TYPE,DIM_PUBLISH_STATE_CODE,IND_NAME,GEO_NAME_SHORT,DIM_SEX,RATE_PER_100000_N,RATE_PER_100000_NL,RATE_PER_100000_NU
0,361734EVIOLENCE_HOMICIDERATE,VIOLENCE_HOMICIDERATE,361734E,VIOLENCE_HOMICIDERATE,2000,YEAR,854,COUNTRY,PUBLISHED,Homicide deaths,Burkina Faso,FEMALE,5.774370,2.988389,10.143787
1,361734EVIOLENCE_HOMICIDERATE,VIOLENCE_HOMICIDERATE,361734E,VIOLENCE_HOMICIDERATE,2000,YEAR,858,COUNTRY,PUBLISHED,Homicide deaths,Uruguay,FEMALE,2.346943,1.869901,2.960971
2,361734EVIOLENCE_HOMICIDERATE,VIOLENCE_HOMICIDERATE,361734E,VIOLENCE_HOMICIDERATE,2000,YEAR,860,COUNTRY,PUBLISHED,Homicide deaths,Uzbekistan,FEMALE,1.777351,1.507913,2.141316
3,361734EVIOLENCE_HOMICIDERATE,VIOLENCE_HOMICIDERATE,361734E,VIOLENCE_HOMICIDERATE,2000,YEAR,862,COUNTRY,PUBLISHED,Homicide deaths,Venezuela (Bolivarian Republic of),FEMALE,7.328798,6.547457,8.121584
4,361734EVIOLENCE_HOMICIDERATE,VIOLENCE_HOMICIDERATE,361734E,VIOLENCE_HOMICIDERATE,2000,YEAR,882,COUNTRY,PUBLISHED,Homicide deaths,Samoa,FEMALE,2.488746,1.147622,4.792777

In [92]:
df_homicide = df_homicide[['GEO_NAME_SHORT', 'DIM_TIME', 'RATE_PER_100000_N']]
df_homicide = df_homicide.rename(columns={'Value': 'HomicideRate'})

In [93]:
df_gdp_raw  = pd.read_csv("C:\\Users\\rohin\\Sucide Project\\Raw Datasets\\API_NY.GDP.PCAP.CD_DS2_en_csv_v2_11526-gdp.csv", skiprows=4)
df_gdp_raw .head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,Unnamed: 69
0,Aruba,ABW,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6767.559229,8244.045660,10056.261393,11507.217151,12187.536361,13233.990517,13892.605143,14700.959808,16055.287787,16548.717387,16620.954556,17750.009564,18828.087059,19216.197235,20681.023027,20740.132583,21307.248251,21949.485996,23700.631990,24171.837133,24845.658484,26736.308944,28171.909401,25134.771230,24093.140151,25712.384302,25119.665545,25813.571441,26129.839062,27458.220154,27441.550214,28440.041688,30082.158423,30645.890602,22759.807175,26749.329609,30975.998912,35718.753119,39498.594129,NaN
1,Africa Eastern and Southern,AFE,GDP per capita (current US$),NY.GDP.PCAP.CD,186.089204,186.909053,197.367547,225.400079,208.962717,226.836135,240.911794,243.773593,257.143823,281.578894,276.732924,294.814162,311.465053,389.729024,463.468775,479.078798,468.774522,518.358685,571.617317,634.448116,773.301205,777.627960,725.547511,732.345461,650.346841,554.221296,578.317452,664.791813,704.142066,728.243319,822.402999,864.174086,732.910915,709.323534,700.772126,766.522931,746.787335,767.399412,697.079415,670.424213,706.727261,625.827815,630.512328,815.432296,989.015464,1126.297323,1235.266608,1381.552597,1447.545754,1408.753467,1628.905248,1761.989261,1732.038021,1706.022744,1690.166792,1498.875240,1334.470500,1528.104224,1552.073722,1507.085600,1351.591669,1562.416175,1679.327622,1571.449189,1615.396356,NaN
2,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,174.930991,138.706822,178.954088,198.871116,221.763654,254.184249,274.218554,376.223152,381.733238,452.053705,560.621505,606.694676,651.417134,637.087099,625.054942,565.569730,522.082216,525.469771,491.337221,496.602504,510.787063,356.496214,357.261153,413.757895,NaN,NaN
3,Africa Western and Central,AFW,GDP per capita (current US$),NY.GDP.PCAP.CD,121.936832,127.451040,133.823783,139.004980,148.545883,155.561897,162.107340,144.940804,146.186183,161.917968,218.672141,195.859987,230.068904,280.643967,368.294725,413.366170,480.447260,490.839577,523.781318,624.870707,763.011988,1328.793688,1164.188488,873.979407,738.545691,754.905547,582.885076,583.317520,563.117147,512.477735,593.024667,607.840414,567.153365,574.472939,580.008123,866.731606,1069.590240,1091.831529,1141.486651,523.797280,518.969226,532.972787,619.337335,697.481256,838.213392,999.770023,1234.641856,1405.880188,1666.520483,1453.495284,1662.633658,1844.054367,1941.118243,2131.606091,2221.350338,1860.727686,1630.039439,1574.230564,1720.140092,2216.385055,2030.861659,2112.794076,2138.473153,1841.855064,1411.337029,NaN
4,Angola,AGO,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,729.111965,657.982649,634.221467,636.832811,650.491094,772.468833,697.526602,770.101140,807.439628,907.747893,965.866840,881.919488,668.706017,449.727895,334.973590,404.294818,531.115367,521.702915,429.188127,392.725539,563.733796,533.586202,999.065856,1133.663320,1451.471179,2145.886211,2930.444286,3515.056790,4578.155265,3645.148466,4101.637156,5184.152691,5702.453063,5688.579162,5649.687625,3641.728939,2051.814621,2790.718869,2860.093648,2493.678844,1759.356199,2303.908127,3682.113151,2916.136633,2665.874448,NaN

In [94]:
df_gdp_raw.columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022',
       '2023', '2024', 'Unnamed: 69'],
      dtype='object')

In [95]:
df_gdp_raw = df_gdp_raw.drop(
    columns=['Country Code', 'Indicator Name', 'Indicator Code'],
    errors='ignore'
)

In [96]:
df_gdp = df_gdp_raw.melt(
    id_vars=['Country Name'],
    var_name='Year',
    value_name='GDP_per_capita'
)

In [97]:
df_gdp.head()

                  Country Name  Year  GDP_per_capita
0                        Aruba  1960             NaN
1  Africa Eastern and Southern  1960      186.089204
2                  Afghanistan  1960             NaN
3   Africa Western and Central  1960      121.936832
4                       Angola  1960             NaN

In [98]:
df_gdp['Year'] = pd.to_numeric(df_gdp['Year'], errors='coerce')
df_gdp = df_gdp.dropna(subset=['Year'])

df_gdp['Year'] = df_gdp['Year'].astype(int)

df_gdp = df_gdp.rename(columns={'Country Name': 'Country'})

In [99]:
df_gdp = df_gdp[
    (df_gdp['Year'] >= 2000) &
    (df_gdp['Year'] <= 2024)
]

In [100]:
df_gdp.info()
df_gdp.head()
df_gdp.tail()

<class 'pandas.core.frame.DataFrame'>
Index: 6650 entries, 10640 to 17289
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country         6650 non-null   object
 1   Year            6650 non-null   int32
 2   GDP_per_capita  6434 non-null   float64
dtypes: float64(1), int32(1), object(1)
memory usage: 181.8+ KB

            Country  Year  GDP_per_capita
17285        Kosovo  2024     7023.065985
17286   Yemen, Rep.  2024             NaN
17287  South Africa  2024     6267.186814
17288        Zambia  2024     1187.109434
17289      Zimbabwe  2024     2497.203322

In [101]:
df_suicide = df_suicide.rename(columns={
    'GEO_NAME_SHORT': 'Country',
    'DIM_TIME': 'Year'
})

In [102]:
df_alcohol = df_alcohol.rename(columns={
    'GEO_NAME_SHORT': 'Country',
    'DIM_TIME': 'Year'
})

In [103]:
df_homicide = df_homicide.rename(columns={
    'GEO_NAME_SHORT': 'Country',
    'DIM_TIME': 'Year'
})

In [104]:
df_gdp = df_gdp.rename(columns={
    'Country Name': 'Country'
})

In [105]:
print("Suicide rows:", len(df_suicide))
print("Alcohol rows:", len(df_alcohol))
print("Homicide rows:", len(df_homicide))
print("GDP rows:", len(df_gdp))

Suicide rows: 4304
Alcohol rows: 5405
Homicide rows: 12936
GDP rows: 6650

In [106]:
print("Suicide countries:", df_suicide['Country'].nunique())
print("Alcohol countries:", df_alcohol['Country'].nunique())
print("Homicide countries:", df_homicide['Country'].nunique())
print("GDP countries:", df_gdp['Country'].nunique())

Suicide countries: 196
Alcohol countries: 231
Homicide countries: 196
GDP countries: 266

In [107]:
print(sorted(df_suicide['Country'].unique())[:20])
print(sorted(df_gdp['Country'].unique())[:20])

['Afghanistan', 'Africa', 'Albania', 'Algeria', 'Americas', 'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin']
['Afghanistan', 'Africa Eastern and Southern', 'Africa Western and Central', 'Albania', 'Algeria', 'American Samoa', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Arab World', 'Argentina', 'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas, The', 'Bahrain', 'Bangladesh', 'Barbados']

In [108]:
def clean_country_names(df):
    df['Country'] = (
        df['Country']
        .astype(str)
        .str.strip()
        .str.replace(r'\s+', ' ', regex=True)
    )
    return df

df_suicide = clean_country_names(df_suicide)
df_alcohol = clean_country_names(df_alcohol)
df_homicide = clean_country_names(df_homicide)
df_gdp = clean_country_names(df_gdp)

In [109]:
for df in [df_suicide, df_alcohol, df_homicide, df_gdp]:
    df['Year'] = pd.to_numeric(df['Year'], errors='coerce').astype('Int64')

In [110]:
df_suicide = df_suicide.dropna(subset=['Year'])
df_alcohol = df_alcohol.dropna(subset=['Year'])
df_homicide = df_homicide.dropna(subset=['Year'])
df_gdp = df_gdp.dropna(subset=['Year'])

In [111]:
countries_common = (
    set(df_suicide['Country'])
    & set(df_alcohol['Country'])
    & set(df_homicide['Country'])
    & set(df_gdp['Country'])
)

len(countries_common), list(sorted(countries_common))[:10]

(158,
 ['Afghanistan',
  'Albania',
  'Algeria',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan'])

In [112]:
df_suicide = df_suicide[df_suicide['Country'].isin(countries_common)]
df_alcohol = df_alcohol[df_alcohol['Country'].isin(countries_common)]
df_homicide = df_homicide[df_homicide['Country'].isin(countries_common)]
df_gdp = df_gdp[df_gdp['Country'].isin(countries_common)]

In [113]:
years_common = (
    set(df_suicide['Year'])
    & set(df_alcohol['Year'])
    & set(df_homicide['Year'])
    & set(df_gdp['Year'])
)

min(years_common), max(years_common)

(2000, 2021)

In [114]:
df_suicide = df_suicide[df_suicide['Year'].isin(years_common)]
df_alcohol = df_alcohol[df_alcohol['Year'].isin(years_common)]
df_homicide = df_homicide[df_homicide['Year'].isin(years_common)]
df_gdp = df_gdp[df_gdp['Year'].isin(years_common)]

In [115]:
df_panel = (
    df_suicide
    .merge(df_alcohol, on=['Country', 'Year'], how='inner')
    .merge(df_homicide, on=['Country', 'Year'], how='inner')
    .merge(df_gdp, on=['Country', 'Year'], how='inner')
)

In [116]:
df_panel.head()
df_panel.shape

(10410, 6)

In [117]:
df_panel.head()

,Country,Year,RATE_PER_100000_N_x,RATE_PER_CAPITA_N,RATE_PER_100000_N_y,GDP_per_capita
0,World,2000,12.520139,4.880508,3.354623,5501.264218
1,World,2000,12.520139,4.880508,12.175367,5501.264218
2,World,2000,12.520139,4.880508,7.788651,5501.264218
3,Afghanistan,2000,4.356148,0.004656,2.410668,174.930991
4,Afghanistan,2000,4.356148,0.004656,18.410191,174.930991

In [118]:
df_panel = df_panel.sort_values(['Country', 'Year']).reset_index(drop=True)

In [121]:
df_panel = df_panel.rename(columns={
    'RATE_PER_100000_N_x': 'SuicideRate',
    'RATE_PER_CAPITA_N': 'AlcoholRate',
    'RATE_PER_100000_N_y': 'HomicideRate'
})

In [122]:
df_panel.head()

,Country,Year,SuicideRate,AlcoholRate,HomicideRate,GDP_per_capita,SuicideRate_diff
0,Afghanistan,2000,4.356148,0.004656,2.410668,174.930991,NaN
1,Afghanistan,2000,4.356148,0.004656,18.410191,174.930991,0.000000
2,Afghanistan,2000,4.356148,0.004656,10.433863,174.930991,0.000000
3,Afghanistan,2001,4.383031,0.004656,2.491126,138.706822,0.026883
4,Afghanistan,2001,4.383031,0.004656,18.684510,138.706822,0.000000

In [123]:
df_panel['SuicideRate_diff'] = (
    df_panel
    .groupby('Country')['SuicideRate']
    .diff()
)

In [124]:
df_panel = df_panel.dropna().reset_index(drop=True)

In [126]:
for col in ['AlcoholRate', 'HomicideRate', 'GDP_per_capita']:
    df_panel[f'{col}_roll3'] = (
        df_panel
        .groupby('Country')[col]
        .rolling(window=3)
        .mean()
        .reset_index(level=0, drop=True)
    )

In [127]:
df_panel = df_panel.dropna().reset_index(drop=True)

In [128]:
df_panel.groupby('Country').size()

Country
Afghanistan            63
Albania                63
Algeria                63
Angola                 63
Antigua and Barbuda    45
                       ..
Vanuatu                63
Viet Nam               63
World                  63
Zambia                 63
Zimbabwe               63
Length: 158, dtype: int64

In [134]:
df_train = df_panel[df_panel['Country'] != 'South Africa']
df_sa_panel = df_panel[df_panel['Country'] == 'South Africa'].copy()

In [135]:
features = [
    'AlcoholRate_roll3',
    'HomicideRate_roll3',
    'GDP_per_capita_roll3'
]

X_train = df_train[features]
y_train = df_train['SuicideRate_diff']

X_sa = df_sa_panel[features]
y_sa = df_sa_panel['SuicideRate_diff']

In [136]:
from sklearn.linear_model import Ridge

model = Ridge(alpha=100)
model.fit(X_train, y_train)

Ridge(alpha=100)

In [137]:
sa_preds = model.predict(X_sa)

df_sa_panel['Predicted_diff'] = sa_preds
df_sa_panel[['Year', 'SuicideRate_diff', 'Predicted_diff']].head()

      Year  SuicideRate_diff  Predicted_diff
8202  2001          0.113145       -0.028925
8203  2001          0.000000       -0.028914
8204  2001          0.000000       -0.028925
8205  2002          1.353199       -0.028277
8206  2002          0.000000       -0.026159

In [138]:
df_sa_panel['Predicted_SuicideRate'] = (
    df_sa_panel['SuicideRate'].shift(1) + df_sa_panel['Predicted_diff']
)

In [139]:
df_panel.to_csv("panel_dataset_ready.csv", index=False)

In [141]:
df_sa_panel.to_csv("df_sa_panel_dataset_ready.csv", index=False)