In [26]:
import pandas as pd

In [2]:
df_suicide = pd.read_csv("C:\\Users\\rohin\\Sucide Project\\Datasets\\16BBF41_ALL_LATEST.csv")
df_final = pd.read_csv("C:\\Users\\rohin\\Sucide Project\\Merged data\\final_model_dataset.csv")

In [3]:
df_suicide.head()
df_suicide.columns

Index(['IND_ID', 'IND_CODE', 'IND_UUID', 'IND_PER_CODE', 'DIM_TIME',
       'DIM_TIME_TYPE', 'DIM_GEO_CODE_M49', 'DIM_GEO_CODE_TYPE',
       'DIM_PUBLISH_STATE_CODE', 'IND_NAME', 'GEO_NAME_SHORT', 'DIM_SEX',
       'DIM_AGE', 'RATE_PER_100000_N', 'RATE_PER_100000_NL',
       'RATE_PER_100000_NU'],
      dtype='object')

In [4]:
df_suicide.head()

,IND_ID,IND_CODE,IND_UUID,IND_PER_CODE,DIM_TIME,DIM_TIME_TYPE,DIM_GEO_CODE_M49,DIM_GEO_CODE_TYPE,DIM_PUBLISH_STATE_CODE,IND_NAME,GEO_NAME_SHORT,DIM_SEX,DIM_AGE,RATE_PER_100000_N,RATE_PER_100000_NL,RATE_PER_100000_NU
0,16BBF41SDGSUICIDE,SDGSUICIDE,16BBF41,SDGSUICIDE,2000,YEAR,1,GLOBAL,PUBLISHED,Suicide deaths,World,FEMALE,TOTAL,8.800814,6.116331,10.530853
1,16BBF41SDGSUICIDE,SDGSUICIDE,16BBF41,SDGSUICIDE,2000,YEAR,1,GLOBAL,PUBLISHED,Suicide deaths,World,MALE,TOTAL,16.199777,13.242620,18.696946
2,16BBF41SDGSUICIDE,SDGSUICIDE,16BBF41,SDGSUICIDE,2000,YEAR,1,GLOBAL,PUBLISHED,Suicide deaths,World,TOTAL,TOTAL,12.520139,9.695973,14.631939
3,16BBF41SDGSUICIDE,SDGSUICIDE,16BBF41,SDGSUICIDE,2000,YEAR,4,COUNTRY,PUBLISHED,Suicide deaths,Afghanistan,FEMALE,TOTAL,2.910393,1.485886,5.835807
4,16BBF41SDGSUICIDE,SDGSUICIDE,16BBF41,SDGSUICIDE,2000,YEAR,4,COUNTRY,PUBLISHED,Suicide deaths,Afghanistan,MALE,TOTAL,5.793457,3.109532,9.464380

In [18]:
df_sa = df_suicide[
    (df_suicide["GEO_NAME_SHORT"] == "South Africa") &
    (df_suicide["DIM_SEX"] == "TOTAL") &
    (df_suicide["DIM_AGE"] == "TOTAL")
]

In [19]:
df_sa_clean = df_sa[["DIM_TIME", 
                      "RATE_PER_100000_N", 
                      "RATE_PER_100000_NL", 
                      "RATE_PER_100000_NU"]].copy()

df_sa_clean.columns = ["Year", "SuicideRate", "SuicideRate_Lower", "SuicideRate_Upper"]

In [22]:
df_merged = df_final.merge(df_sa_clean, on="Year", how="left")

In [23]:
df_merged

,Year,AlcoholConsumption,HomicideRate,GDP_per_capita,Current health expenditure (% of GDP)_x,Current health expenditure per capita (current US$)_x,"Unemployment, total (% of total labor force) (modeled ILO estimate)_x",Current health expenditure (% of GDP)_y,Current health expenditure per capita (current US$)_y,"Unemployment, total (% of total labor force) (modeled ILO estimate)_y",SuicideRate,SuicideRate_Lower,SuicideRate_Upper
0,1975,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1976,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1977,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1978,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1979,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1981,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1984,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1985,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1986,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1988,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1989,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,1991,NaN,NaN,NaN,NaN,NaN,23.002,NaN,NaN,23.002,NaN,NaN,NaN
17,1992,NaN,NaN,NaN,NaN,NaN,23.262,NaN,NaN,23.262,NaN,NaN,NaN
18,1993,NaN,NaN,NaN,NaN,NaN,23.179,NaN,NaN,23.179,NaN,NaN,NaN
19,1994,NaN,NaN,NaN,NaN,NaN,22.942,NaN,NaN,22.942,NaN,NaN,NaN
20,1995,NaN,NaN,NaN,NaN,NaN,22.647,NaN,NaN,22.647,NaN,NaN,NaN
21,1996,NaN,NaN,NaN,NaN,NaN,22.480,NaN,NaN,22.480,NaN,NaN,NaN
22,1997,NaN,NaN,NaN,NaN,NaN,22.518,NaN,NaN,22.518,NaN,NaN,NaN
23,1998,NaN,NaN,NaN,NaN,NaN,22.673,NaN,NaN,22.673,NaN,NaN,NaN
24,1999,NaN,NaN,NaN,NaN,NaN,22.791,NaN,NaN,22.791,NaN,NaN,NaN
25,2000,8.742056,45.012212,3217.846934,7.336619,236.081146,22.714,7.336619,236.081146,22.714,13.132524,10.616174,15.492517
26,2001,8.742056,45.090413,2847.151919,7.123279,202.810654,22.605,7.123279,202.810654,22.605,13.245669,10.820065,15.693809
27,2002,8.483838,47.472567,2688.236760,6.677745,179.513550,22.547,6.677745,179.513550,22.547,14.598869,11.962040,17.234773
28,2003,8.366666,44.799503,4062.217560,7.040982,286.019989,22.629,7.040982,286.019989,22.629,15.759870,12.819716,18.513331
29,2004,8.343871,44.530240,5221.463337,6.938416,362.286621,22.538,6.938416,362.286621,22.538,16.074981,13.053871,18.851862
30,2005,8.402676,18.905256,5836.876633,6.862162,400.535583,22.461,6.862162,400.535583,22.461,15.636315,12.685922,18.308753
31,2006,8.470212,17.915438,6077.382934,6.876509,417.911743,22.324,6.876509,417.911743,22.324,16.099597,13.059278,18.687917
32,2007,8.476132,16.741810,6591.855360,6.905108,455.174988,22.287,6.905108,455.174988,22.287,15.960853,12.990243,18.628283
33,2008,8.391783,16.464638,6184.754743,7.148323,442.106262,22.407,7.148323,442.106262,22.407,16.842257,13.632509,19.740628
34,2009,8.248683,15.519685,6374.705600,7.649415,487.627747,23.523,7.649415,487.627747,23.523,16.407856,13.420787,19.158675
35,2010,8.239292,14.266698,7973.471958,7.793582,621.419067,24.683,7.793582,621.419067,24.683,18.779493,15.861610,22.270309
36,2011,8.336959,13.718138,8646.055711,7.944344,686.872437,24.639,7.944344,686.872437,24.639,17.294789,14.636045,20.583179
37,2012,8.421343,13.446773,8076.976785,8.004289,646.499207,24.727,8.004289,646.499207,24.727,18.180492,15.268520,21.463019
38,2013,8.441097,13.408549,7331.654674,8.103223,593.801575,24.561,8.103223,593.801575,24.561,18.697336,15.517204,22.167239
39,2014,8.451979,13.510317,6856.731371,7.871366,539.307800,24.890,7.871366,539.307800,24.890,20.072039,16.563980,24.055178
40,2015,8.443988,13.704022,6112.273825,8.053042,491.906525,25.149,8.053042,491.906525,25.149,20.744650,17.014795,25.247098
41,2016,8.397732,13.955669,5651.205852,8.079594,456.569366,26.536,8.079594,456.569366,26.536,19.584156,15.958505,24.579817
42,2017,NaN,14.477758,6618.335083,7.977112,527.520203,27.035,7.977112,527.520203,27.035,18.186891,14.729601,22.728487
43,2018,8.451479,13.546167,6914.178032,8.081965,558.801392,26.906,8.081965,558.801392,26.906,19.152647,15.294827,23.124624
44,2019,7.939926,13.508287,6533.711210,8.246526,538.804260,28.468,8.246526,538.804260,28.468,20.140313,15.964357,24.109744
45,2020,NaN,12.961973,5580.603831,9.013292,503.467590,29.217,9.013292,503.467590,29.217,21.099576,16.658875,25.314198
46,2021,7.791870,12.533244,6843.399419,8.674328,592.534180,34.007,8.674328,592.534180,34.007,22.295801,17.174630,26.523387
47,2022,7.791870,NaN,6523.410978,8.770866,569.840759,33.268,8.770866,569.840759,33.268,NaN,NaN,NaN
48,2023,NaN,NaN,NaN,NaN,NaN,32.098,NaN,NaN,32.098,NaN,NaN,NaN
49,2024,NaN,NaN,NaN,NaN,NaN,33.168,NaN,NaN,33.168,NaN,NaN,NaN

In [24]:
df_merged.to_csv("final_model_dataset_UPDATED.csv", index=False)

In [27]:
df_filtered = df_merged[df_merged["Year"] >= 2000].copy()

In [28]:
df_filtered.reset_index(drop=True, inplace=True)

In [29]:
df_filtered.head()

,Year,AlcoholConsumption,HomicideRate,GDP_per_capita,Current health expenditure (% of GDP)_x,Current health expenditure per capita (current US$)_x,"Unemployment, total (% of total labor force) (modeled ILO estimate)_x",Current health expenditure (% of GDP)_y,Current health expenditure per capita (current US$)_y,"Unemployment, total (% of total labor force) (modeled ILO estimate)_y",SuicideRate,SuicideRate_Lower,SuicideRate_Upper
0,2000,8.742056,45.012212,3217.846934,7.336619,236.081146,22.714,7.336619,236.081146,22.714,13.132524,10.616174,15.492517
1,2001,8.742056,45.090413,2847.151919,7.123279,202.810654,22.605,7.123279,202.810654,22.605,13.245669,10.820065,15.693809
2,2002,8.483838,47.472567,2688.236760,6.677745,179.513550,22.547,6.677745,179.513550,22.547,14.598869,11.962040,17.234773
3,2003,8.366666,44.799503,4062.217560,7.040982,286.019989,22.629,7.040982,286.019989,22.629,15.759870,12.819716,18.513331
4,2004,8.343871,44.530240,5221.463337,6.938416,362.286621,22.538,6.938416,362.286621,22.538,16.074981,13.053871,18.851862

In [30]:
df_filtered.to_csv("final_model_dataset_2000_onward.csv", index=False)